name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildtest:
    runs-on: windows-latest
    steps:
      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Restore packages
        run: dotnet restore

      - name: Build Debug
        run: dotnet build --configuration Debug

      - name: Run tests
        run: dotnet test --no-build --collect "Code Coverage"

  buildrelease:
    runs-on: windows-latest
    steps:
      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Restore packages
        run: dotnet restore

      - name: Build Release
        run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true

      - name: Pack Release
        run: dotnet pack --configuration Release --no-build

      - name: Upload NuGet package
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: out/*.*nupkg
          if-no-files-found: error
